[workspace]
members = [
    "tubefeeder-extractor-join",
    "tubefeeder-extractor-core",
    "tubefeeder-extractor-filter",
    "platform-youtube",
    "platform-test",
    "observer",
    "playlist"
]
