[workspace]
members = [
    "tf_core",
    "tf_join",
    "tf_filter",
    "tf_observer",
    "tf_playlist",
    "tf_utils",
    "tf_platform_youtube",
    "tf_platform_peertube",
    "tf_platform_lbry",
    "tf_platform_test"
]
