[workspace]
members = [
    "tubefeeder-extractor-join",
    "tubefeeder-extractor-core",
    "tubefeeder-extractor-youtube",
    "tubefeeder-extractor-test",
    "tubefeeder-extractor-filter",
    "observer"
]
